### ISSUE TITLE
Implement Pigeonhole Sort

### ISSUE THREAD

**Issue by marie-yau** [marie-yau/Sorting-Algorithms#14]

**Comment by Asmeble** [comment]
try this:
"""
def pigeonhole_sort(a):
	mi = min(a)
	size = max(a) - mi + 1
	holes = [0] * size
	for x in a:
		holes[x - mi] += 1
	i = 0
	for count in xrange(size):
		while holes[count] > 0:
			holes[count] -= 1
			a[i] = count + mi
			i += 1
""""
